# Generated by Django 5.1.2 on 2024-11-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="expense_categories",
            field=models.TextField(
                blank=True,
                default="Food,Rent,Transport,Entertainment",
                help_text="Comma-separated expense categories",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="income_categories",
            field=models.TextField(
                blank=True,
                default="Salary,Investment,Bonus",
                help_text="Comma-separated income categories",
            ),
        ),
    ]
